# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.0.0

test-site: &test-site
  docker:
    - image: circleci/node:10-browsers
  working_directory: ~/topmonks-webs
  steps:
    - checkout
    - attach_workspace:
        at: ~/topmonks-webs
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
    - run:
        command: yarn run http-server ./public/$HOST
        background: true
    - run: |
        mkdir results
        yarn test:lighthouse
        yarn test:ava
        yarn test:broken-links:$HOST
    - store_artifacts:
        path: ./results
    - store_test_results:
        path: ./results

s3-deploy: &s3-deploy
  docker:
    - image: cibuilds/aws:latest
  working_directory: ~/topmonks-webs

jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run build
      - run: |
          mkdir results
          yarn test
      - store_artifacts:
          path: ./results
      - store_test_results:
          path: ./results
      - persist_to_workspace:
          root: .
          paths: public

  test-www-topmonks-com:
    <<: *test-site
    environment:
      HOST: www.topmonks.com

  test-blockchain-topmonks-com:
    <<: *test-site
    environment:
      HOST: blockchain.topmonks.com

  test-studio-topmonks-com:
    <<: *test-site
    environment:
      HOST: studio.topmonks.com

  test-www-topmonks-cz:
    <<: *test-site
    environment:
      HOST: www.topmonks.cz

  test-caffe-topmonks-cz:
    <<: *test-site
    environment:
      HOST: caffe.topmonks.cz

  test-prodeti-topmonks-cz:
    <<: *test-site
    environment:
      HOST: prodeti.topmonks.cz

  deploy-prodeti-topmonks-cz:
    <<: *s3-deploy
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E3FDER5NIOLAD2
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - run:
          name: Deploy to S3
          command: aws s3 sync public/prodeti.topmonks.cz s3://prodeti.topmonks.cz/
      - run:
          name: Invalidate CDN distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*

  deploy-blockchain-topmonks-com:
    <<: *s3-deploy
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E8FIHBRFAUTJQ
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - run:
          name: Deploy to S3
          command: aws s3 sync public/blockchain.topmonks.com s3://blockchain.topmonks.com/
      - run:
          name: Invalidate CDN distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*

  deploy-studio-topmonks-com:
    <<: *s3-deploy
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E3E7VE5619MYLH
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - run:
          name: Deploy to S3
          command: aws s3 sync public/studio.topmonks.com s3://studio.topmonks.com/
      - run:
          name: Invalidate CDN distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*

  deploy-www-topmonks-com:
    <<: *s3-deploy
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: EMNWZWEX2M2BH
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - run:
          name: Deploy to S3
          command: aws s3 sync public/www.topmonks.com s3://www.topmonks.com/
      - run:
          name: Invalidate CDN distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*

  deploy-www-topmonks-cz:
    <<: *s3-deploy
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E1CX5IMQ3B6G4W
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - run:
          name: Deploy to S3
          command: aws s3 sync public/www.topmonks.cz s3://www.topmonks.cz/
      - run:
          name: Invalidate CDN distribution
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*

  deploy-test-caffe-topmonks-com:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/topmonks-webs
    steps:
      - checkout
      - attach_workspace:
          at: ~/topmonks-webs
      - pulumi/login
      - run:
          command: |
            cd .pulumi
            echo $PWD
            npm install
            npm run build
      - pulumi/update:
          working_directory: .pulumi
          stack: topmonks/topmonks-webs-prod
          skip-preview: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
#      - test-www-topmonks-com:
#          requires:
#            - build
#      - test-blockchain-topmonks-com:
#          requires:
#            - build
#      - test-studio-topmonks-com:
#          requires:
#            - build
#      - test-www-topmonks-cz:
#          requires:
#            - build
#      - test-caffe-topmonks-cz:
#          requires:
#            - build
#      - test-prodeti-topmonks-cz:
#          requires:
#            - build
#      - deploy-prodeti-topmonks-cz:
#          context: org-global
#          requires:
#            - test-prodeti-topmonks-cz
#          filters:
#            branches:
#              only: master
#      - deploy-www-topmonks-com:
#          context: org-global
#          requires:
#            - test-www-topmonks-com
#          filters:
#            branches:
#              only: master
#      - deploy-www-topmonks-cz:
#          context: org-global
#          requires:
#            - test-www-topmonks-cz
#          filters:
#            branches:
#              only: master
#      - deploy-blockchain-topmonks-com:
#          context: org-global
#          requires:
#            - test-blockchain-topmonks-com
#          filters:
#            branches:
#              only: master
#      - deploy-studio-topmonks-com:
#          context: org-global
#          requires:
#            - test-studio-topmonks-com
#          filters:
#            branches:
#              only: master
      - deploy-test-caffe-topmonks-com:
          context: org-global
          requires:
          - build
          filters:
            branches:
              only: feature/pulumi-deploy
